### ISSUE TITLE
Using sigma plugins

### ISSUE THREAD

**Issue by iankloo** [jjallaire/sigma#5]
This is great - I'm trying to expand on this by adding in some plugin functionality.  Namely, I'd like to be able to get the neighborhood plugin worked in.  I'm having some trouble figuring out how/where to do that...

Should I be editing the sigma.js file?  The sigma.js.min file?  

Trying to learn javascript from the ground up while trying to learn how to get R to talk to it...

**Comment by jjallaire** [comment]
I think plugins are just additional dependencies you need to specify in the
yaml config file. Specify them after the sigma.js file and they will be
automatically included by htmlwidgets (you can confirm this by doing a view
source after you've added the plugins to the yaml file).
